name: chickychickyplanner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.1.2
  go_router: ^14.1.3
  google_fonts: ^6.2.1
  http: ^1.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  uuid: ^4.4.0
  velocity_x: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
flutter:
  uses-material-design: true
  assets:  
    - lib/images/Fire_element/
    - lib/images/Lightning_element/
    - lib/images/Plant_element/
    - lib/images/Poison_element/
    - lib/images/Water_element/
    - lib/images/Decorations/
    - lib/images/Icons/Bottom_Navigator_Interacted_Icons/
    - lib/images/Icons/Bottom_Navigator_Default_Icons/
    - lib/images/
    - lib/env/.env
