final List<List<String>> images = [
  [
    'lib/images/Wooden_Axe.png',
    'lib/images/Wooden_Hoe.png',
    'lib/images/Wooden_Pickaxe.png',
    'lib/images/Wooden_Shovel.png',
    'lib/images/Wooden_Sword.png',
  ],
  [
    'lib/images/Stone_Axe.png',
    'lib/images/Stone_Hoe.png',
    'lib/images/Stone_Pickaxe.png',
    'lib/images/Stone_Shovel.png',
    'lib/images/Stone_Sword.png',
  ],
  [
    'lib/images/Iron_Axe.png',
    'lib/images/Iron_Hoe.png',
    'lib/images/Iron_Pickaxe.png',
    'lib/images/Iron_Shovel.png',
    'lib/images/Iron_Sword.png',
  ],
  [
    'lib/images/Golden_Axe.png',
    'lib/images/Golden_Hoe.png',
    'lib/images/Golden_Pickaxe.png',
    'lib/images/Golden_Shovel.png',
    'lib/images/Golden_Sword.png',
  ],
  [
    'lib/images/Diamond_Axe.png',
    'lib/images/Diamond_Hoe.png',
    'lib/images/Diamond_Pickaxe.png',
    'lib/images/Diamond_Shovel.png',
    'lib/images/Diamond_Sword.png',
  ],
  [
    'lib/images/Netherite_Axe.png',
    'lib/images/Netherite_Hoe.png',
    'lib/images/Netherite_Pickaxe.png',
    'lib/images/Netherite_Shovel.png',
    'lib/images/Netherite_Sword.png',
  ],
];

List<String> rarity = [
  'Common',
  'Uncommon',
  'Rare',
  'Epic',
  'Masterwork',
  'Legendary'
];

List<String> name = [
  'Axe',
  'Hoe',
  'Pickaxe',
  'Shovel',
  'Sword',
];
